### ISSUE TITLE
A question about the testing result.

### ISSUE THREAD

**Issue by QWTforGithub** [humanpose1/MS-SVConv#15]
Hi, first of all, thank you for your help many times before. I don't mean to be rude, but I tested your published model 'MS_SVCONV_B2cm_X2_3head.pt 'at different sample points (5000, 2500, 1000, 500, 250) and I could only get between 92-96% of data (95.3%, 95.1%, 94.7%, 94.4%, 92.1%), not as good performance as in your paper. My test setup is based on what you posted. Is there something wrong with my Settings? I tested SpinNet, FCGF and other models, and the results were close to the paper. I don't think it's the environment.

**Comment by QWTforGithub** [comment]
> Hi @QWTforGithub I have a small request. Can you try with [this model](https://cloud.mines-paristech.fr/index.php/s/osD3Ji47o0NCDAs).

Sorry, I still can't get good results(96.5%), even using the model you just provided. I notice **data= fragment3DMatch_sparse** instead of **data= Fragment3DMatch**. I tried re-removing **matches folder** and **fragments folder** from the **process folder**, but it still didn't work. I can only use the data that appears in your paper, and the data that doesn't I use the data that I run myself. I'm sorry about that.

Thank you again for your help for many times. I believe your data is true.
Best wish.

**Comment by humanpose1** [comment]
Hi @QWTforGithub ,

I re tested and I also got around 96.5% with the models I gave you and the code.  Right know I have not yet pinpointed exactly the problem. But with an old version of torch-points3d, I can reproduce the FMR of ~98%.
```
git clone https://github.com/humanpose1/deeppointcloud-benchmarks.git
git checkout -b "MS_SVCONV_B2cm_X2_3head" d079374da05506762f32bb7b090f35be86a90760
```
But it use an old version of omegaconf, hydra, torch, and an old version of torchsparse also (version 1.2 instead of 1.4). And it works with this [model](https://cloud.mines-paristech.fr/index.php/s/kFGIqiY9Ky5OeiB).

When I will have time, I will find the problem (is it the torchsparse version ,my old code, or something else ?) and fix it so it can work with the last version of tp3d.
Best,.

**Comment by humanpose1** [comment]
Hi @QWTforGithub ,

I re tested and I also got around 96.5% with the models I gave you and the code.  Right know I have not yet pinpointed exactly the problem. But with an old version of torch-points3d, I can reproduce the FMR of ~98%.
```
git clone https://github.com/humanpose1/deeppointcloud-benchmarks.git
git checkout -b "MS_SVCONV_B2cm_X2_3head" d079374da05506762f32bb7b090f35be86a90760
```
But it use an old version of omegaconf, hydra, torch, and an old version of torchsparse also (version 1.2 instead of 1.4). And it works with this [model](https://cloud.mines-paristech.fr/index.php/s/kFGIqiY9Ky5OeiB).

When I will have time, I will find the problem (is it the torchsparse version ,my old code, or something else ?) and fix it so it can work with the last version of tp3d.
Best,.

**Comment by QWTforGithub** [comment]
> Hi @QWTforGithub ,
> 
> I re tested and I also got around 96.5% with the models I gave you and the code. Right know I have not yet pinpointed exactly the problem. But with an old version of torch-points3d, I can reproduce the FMR of ~98%.
> 
> ```
> git clone https://github.com/humanpose1/deeppointcloud-benchmarks.git
> git checkout -b "MS_SVCONV_B2cm_X2_3head" d079374da05506762f32bb7b090f35be86a90760
> ```
> 
> But it use an old version of omegaconf, hydra, torch, and an old version of torchsparse also (version 1.2 instead of 1.4). And it works with this [model](https://cloud.mines-paristech.fr/index.php/s/kFGIqiY9Ky5OeiB).
> 
> When I will have time, I will find the problem (is it the torchsparse version ,my old code, or something else ?) and fix it so it can work with the last version of tp3d. Best,.

Ok , thank you for your reply. By the way, Hi, I noticed that the downsampling of training 3DMatch is 0.02 (first_subsampling : 0.02) and when tested, it was 0.02. In general, when we test the model, the training and the testing are usually set up the same way, right? For example, if I train the model with a 0.025 downsample setting, I should also test it with a 0.025 downsample setting.

**Comment by humanpose1** [comment]
Yes, exactly, Even when you change sensors, you should keep the same sampling (When I test MS-SVConv on ETH, I keep the subsampling at 0.02).

**Comment by humanpose1** [comment]
Hi,

With the current version of torch-points3d, I obtain a FMR of 97.4 instead of 98.4 with tau=0.05 on 3DMatch in a supervised setting. However, with tau=0.2, I obtain a FMR of 91.6 instead of 89.9. In other word, the current version is better in terms of FMR with tau=0.2. If you want to get the previous results, you can use the previous version.
